ticketing_system/accounts/urls.py
from django.urls import path
from . import views  


urlpatterns = [
    path('registration', views.user_registration, name='registration'),
    path('login', views.login, name='login'),
    
    path('projects/', views.project_list, name='project_list'),
    path('projects/create/', views.create_project, name='create_project'),
    path('projects/<int:project_id>/edit/', views.edit_project, name='edit_project'),
    path('projects/<int:project_id>/block/', views.block_project, name='block_project'),
    path('projects/<int:project_id>/unblock/', views.unblock_project, name='unblock_project'),
    path('projects/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    path('projects/<int:project_id>/assign/', views.assign_projects, name='assign_project'),

    path('create_ticket/<int:project_id>', views.create_ticket, name='create_ticket'),
    path('ticket/<int:ticket_id>/', views.ticket_detail, name='ticket_detail'),
    path('assigned-tickets/', views.assigned_tickets, name='assigned_tickets'),
    path('ticket/<int:ticket_id>/update/', views.update_ticket_status, name='update_ticket_status'),
    path('ticket/<int:ticket_id>/check/', views.check_ticket, name='check_ticket'),

    path('dashboard/', views.dashboard, name='dashboard'),

    path('profile/', views.update_profile, name='profile'),

    path('logout/', views.logout_view, name='logout'),
]   

ticketing_system/ticketing_system/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from django.urls import re_path
from django.views.static import serve


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if not settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]

ticketing_system/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    email = models.EmailField(max_length=254, unique=True)
    name = models.TextField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    projects = models.ManyToManyField("Project", related_name="assigned_users")

    def __str__(self):
        return self.username


class Project(models.Model):
    STATUS_CHOICES = [
        ("Active", "Active"),
        ("Inactive", "Inactive"),
        ("Completed", "Completed"),
        ("Archived", "Archived"),
    ]

    name = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="Active")
    is_blocked = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Ticket(models.Model):
    STATUS_CHOICES = [
        ("Draft", "Draft"),
        ("Ongoing", "Ongoing"),
        ("Completed", "Completed"),
        ("Archived", "Archived"),
    ]

    name = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    assigned_to = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="Draft")
    comment = models.TextField()

    def __str__(self):
        return self.name


class TicketAttachment(models.Model):
    TICKET_ATTACHMENT_CHOICES = [
        ("Image", "Image"),
        ("Video", "Video"),
        ("Docs", "Docs"),
    ]

    ticket = models.ForeignKey(
        Ticket, on_delete=models.CASCADE, related_name="attachments"
    )
    attachment = models.FileField(upload_to="ticket_attachments/")
    attachment_type = models.CharField(max_length=20, choices=TICKET_ATTACHMENT_CHOICES)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.attachment_type} - {self.uploaded_at}"

ticketing_system/accounts/forms.py
from django import forms
from .models import Project

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description', 'status']

ticketing_system/accounts/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import Project, Ticket, TicketAttachment, User
from datetime import timedelta
from django.utils import timezone
from django.contrib.auth import login as auth_login, logout
from django.contrib.auth.hashers import check_password
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .filters import TicketFilter


# Create your views here.
def user_registration(request):
    if request.method == "POST":
        email = request.POST["email"]
        name = request.POST["name"]
        password = request.POST["password"]
        user = User(email=email, name=name)
        user.username = name
        user.is_staff = True
        user.set_password(password)
        user.save()
    return render(request, "user_registration.html")


def login(request):
    if request.method == "POST":
        email = request.POST["email"]
        password = request.POST["password"]

        # Authenticate the user
        user = User.objects.filter(email=email).first()
        if not user:
            messages.error(request,'Invalid email or password. Please try again.')
            return render(request, "user_login.html")
        
        password_matches = check_password(password, user.password)

        if password_matches:
            auth_login(request, user)
            return redirect("dashboard")
        else:
            # Return an invalid login error
            messages.error(request,'Invalid email or password. Please try again.')
            return render(request, "user_login.html")

    return render(request, "user_login.html")


@login_required(login_url='login')
def logout_view(request):
    logout(request)
    return redirect("login")


@login_required(login_url='login')
def create_project(request):
    if request.method == "POST":
        name = request.POST.get("name")
        description = request.POST.get("description")
        status = request.POST.get("status")
        project = Project(name=name, description=description, status=status)
        project.save()
        return redirect("project_list")
    return render(request, "project_form.html")


@login_required(login_url='login')
def assign_projects(request, project_id):
    if request.method == "POST":
        staff_user_id = request.POST.get("staff_user")
        # project_id = request.POST.get("project")

        # Fetch the staff user and project from the IDs
        staff_user = User.objects.get(pk=staff_user_id)
        project = Project.objects.get(pk=project_id)

        # Assign the project to the staff user
        staff_user.projects.add(project)

        return redirect("project_list")

    staff_users = User.objects.filter(is_staff=True)
    project = get_object_or_404(Project, id=project_id)

    return render(
        request,
        "assign_projects.html",
        {"staff_users": staff_users, "project": project},
    )


@login_required(login_url='login')
def edit_project(request, project_id):
    project = get_object_or_404(Project, id=project_id)

    if request.method == "POST":
        project.name = request.POST.get("name")
        project.description = request.POST.get("description")
        project.status = request.POST.get("status")
        project.save()

        return redirect("project_list")

    return render(request, "edit_project.html", {"project": project})


@login_required(login_url='login')
def block_project(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    project.is_blocked = True
    project.save()
    return redirect("project_list")


@login_required(login_url='login')
def unblock_project(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    project.is_blocked = False
    project.save()
    return redirect("project_list")


@login_required(login_url='login')
def delete_project(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    if project:
        project.delete()
        return redirect("project_list")
    return redirect("project_list")


@login_required(login_url='login')
def project_list(request):
    if request.user.is_superuser:
        projects = Project.objects.all()
    else:
        projects = request.user.projects.all()
    return render(
        request, "project_list.html", {"projects": projects, "user": request.user}
    )


@login_required(login_url='login')
def create_ticket(request, project_id):
    if request.method == "POST":
        name = request.POST["name"]
        description = request.POST["description"]
        assigned_to_id = request.POST["assigned_to"]
        project_id = request.POST["project"]
        status = request.POST["status"]
        attachment_type = request.POST["attachment_type"]

        assigned_to = User.objects.get(pk=assigned_to_id)
        project = Project.objects.get(pk=project_id)

        # Create a new Ticket object
        ticket = Ticket(
            name=name,
            description=description,
            assigned_to=assigned_to,
            project=project,
            status=status,
        )
        ticket.save()

        # Handle attachment upload
        attachment = request.FILES.get("attachment")
        if attachment:
            # Create TicketAttachment object
            ticket_attachment = TicketAttachment(
                ticket=ticket, attachment=attachment, attachment_type=attachment_type
            )
            # Save the attachment
            ticket_attachment.save()

        return redirect("ticket_detail", ticket_id=ticket.id)

    users = User.objects.all()
    project = Project.objects.get(pk=project_id)

    return render(request, "create_ticket.html", {"users": users, "project": project})


@login_required(login_url='login')
def ticket_detail(request, ticket_id):
    ticket = get_object_or_404(Ticket, id=ticket_id)    
    if request.method == "POST":
        comment = request.POST.get('comment')
        ticket.comment = comment
        ticket.status = "Completed"
        ticket.save()
        return redirect("dashboard")
    ticket_attachments = ticket.attachments.all()
    return render(
        request,
        "ticket_detail.html",
        {"ticket": ticket, "ticket_attachments": ticket_attachments},
    )


@login_required(login_url='login')
def assigned_tickets(request):
    allowed_statuses = ["Draft", "Ongoing", "Completed"]
    if request.user.is_superuser:
        assigned_tickets = Ticket.objects.all()
    else:
        assigned_tickets = Ticket.objects.filter(
            assigned_to=request.user, status__in=allowed_statuses
        )

    time_filter = request.GET.get("timeFilter")

    if time_filter == "day":
        assigned_tickets = assigned_tickets.filter(
            created_at__gte=timezone.now() - timedelta(days=1)
        )
    elif time_filter == "week":
        assigned_tickets = assigned_tickets.filter(
            created_at__gte=timezone.now() - timedelta(days=7)
        )
    elif time_filter == "month":
        assigned_tickets = assigned_tickets.filter(
            created_at__gte=timezone.now() - timedelta(days=30)
        )
    return render(
        request, "assigned_tickets.html", {"assigned_tickets": assigned_tickets}
    )


@login_required(login_url='login')
def update_ticket_status(request, ticket_id):
    ticket = get_object_or_404(Ticket, id=ticket_id)
    new_status = request.GET.get("status")
    if new_status in ["Ongoing", "Completed"]:
        ticket.status = new_status
        ticket.save()
    return redirect("dashboard")


def check_ticket(request, ticket_id):
    ticket = get_object_or_404(Ticket, id=ticket_id)    
    if request.method == "POST":
        new_status = request.POST.get("status")
        ticket.status = new_status
        ticket.save()
        return redirect("dashboard")
    ticket_attachments = ticket.attachments.all()
    return render(
        request,
        "check_ticket.html",
        {"ticket": ticket, "ticket_attachments": ticket_attachments},
    )


@login_required(login_url='login')
def dashboard(request):
    if not request.user.is_authenticated:
        return render(request,'404.html')
    total_draft_tickets = Ticket.objects.filter(assigned_to=request.user, status="Draft").count()
    total_ongoing_tickets = Ticket.objects.filter(assigned_to=request.user, status="Ongoing").count()
    total_completed_tickets = Ticket.objects.filter(assigned_to=request.user, status="Completed").count()
    
    allowed_statuses = ["Draft", "Ongoing", "Completed"]
    if request.user.is_superuser:
        assigned_tickets = Ticket.objects.all()
        my_Filter = TicketFilter(request=request.GET, queryset=assigned_tickets)
        assigned_tickets = my_Filter.qs
    else:
        assigned_tickets = Ticket.objects.filter(
            assigned_to=request.user, status__in=allowed_statuses
        )
        
    time_filter = request.GET.get("timeFilter")

    if time_filter == "day":
        assigned_tickets = assigned_tickets.filter(
            created_at__gte=timezone.now() - timedelta(days=1)
        )
        print(assigned_tickets)
        
    elif time_filter == "week":
        assigned_tickets = assigned_tickets.filter(
            created_at__gte=timezone.now() - timedelta(days=7)
        )
        
    elif time_filter == "month":
        assigned_tickets = assigned_tickets.filter(
            created_at__gte=timezone.now() - timedelta(days=30)
        )
        

    return render(
        request,
        "dashboard.html",
        {
            "total_draft_tickets": total_draft_tickets,
            "total_ongoing_tickets": total_ongoing_tickets,
            "total_completed_tickets": total_completed_tickets,
            "assigned_tickets": assigned_tickets,
            "filter": time_filter,
            "my_Filter":my_Filter
        },
    )


@login_required(login_url='login')
def update_profile(request):
    return render(request, "profile.html")

ticketing_system/accounts/templates/assign_projects.html
{% extends 'base.html' %}

{% block title %}
  Project List
{% endblock %}

{% block content %}
  <h2>Assign Project</h2>

  <form method="post" class="my-4">
    {% csrf_token %}

    <div class="form-group row">
      <label for="id_staff_user" class="col-sm-2 col-form-label">Select Staff User:</label>
      <div class="col-sm-4">
        <select id="id_staff_user" name="staff_user" class="form-control">
          {% for user in staff_users %}
            <option value="{{ user.id }}">{{ user.username }}</option>
          {% endfor %}
        </select>
      </div>
    </div>

    <div class="form-group row">
      <label for="id_project" class="col-sm-2 col-form-label">Project Name:</label>
      <div class="col-sm-4">
        <strong><p class="mt-2">{{ project.name }}</p></strong>
      </div>
    </div>

    <button type="submit" class="btn btn-primary">Assign Project</button>
  </form>
{% endblock %}

ticketing_system/accounts/templates/assigned_tickets.html
{% extends 'base.html' %}
{% block title %}
  Project List
{% endblock %}

{% block content %}
        <h2>Assigned Tickets</h2>
        <form method="GET" action="">
            <div class="form-group">
                <label for="timeFilter">Filter by Time:</label>
                <select id="timeFilter" name="timeFilter" class="form-control">
                    <option value="all">All</option>
                    <option value="day">Last 24 Hours</option>
                    <option value="week">Last 7 Days</option>
                    <option value="month">Last 30 Days</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary mb-2">Filter</button>
        </form>

        <div class="row">
            {% for ticket in assigned_tickets %}
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <a href="{% url 'ticket_detail' ticket_id=ticket.id %}">
                                <h5 class="card-title">{{ ticket.name }}</h5>
                                <p class="card-text"><strong>Description:</strong> {{ ticket.description }}</p>
                                <p class="card-text"><strong>Status:</strong> {{ ticket.status }}</p>
                            </a>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 and not forloop.last %}
                    </div><div class="row">
                {% endif %}
            {% empty %}
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text">No assigned tickets found.</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endblock %}

ticketing_system/accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- Custom CSS -->
    <style>
        {% block css %}{% endblock %}
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        {% if user.is_authenticated  %}
            <a class="navbar-brand" href="{% url 'dashboard' %}">Ticketing System</a>
        {% else %}
        <a class="navbar-brand" href="{% url 'login' %}">Ticketing System</a>
        {% endif %}
        <!-- Navbar items -->
        {% if user.is_authenticated  %}
        <ul class="navbar-nav ml-auto">
            <!-- Add other navbar items as needed -->

            <li class="nav-item">
                <a href="{% url 'profile' %}" class="btn btn-dark mr-2">Profile</a>
            </li>

            <li class="nav-item">
                <a href="{% url 'project_list' %}" class="btn btn-dark mr-2">Projects</a>
            </li>
    
            <!-- Logout button -->
            <li class="nav-item">
                <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-dark">Logout</button>
                </form>
            </li>
        </ul>
        {% endif %}
    </nav>
    <div class="container">
        <!-- Navbar -->

        <!-- Content -->
        <div class="container">
            <div class="mt-4">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        
    </div>
    
    <!-- Bootstrap JS and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

ticketing_system/accounts/templates/check_ticket.html
{% extends 'base.html' %}
{% block title %}
Ticket Details
{% endblock %}

{% block content %}
        <h2>Ticket Details</h2><br>
        <h3>{{ ticket.name }}</h3>
        <p><strong>Description:</strong> {{ ticket.description }}</p>
        <p><strong>Assigned To:</strong> {{ ticket.assigned_to }}</p>
        <p><strong>Project:</strong> {{ ticket.project }}</p>
        <p><strong>Status:</strong> {{ ticket.status }}</p>
        <p><strong>Creared At:</strong> {{ ticket.created_at }}</p>
        <p><strong>Work Description:</strong> {{ ticket.comment }} </p>

        <hr>

        <h3>Attachments:</h3>
        <ul class="list-group">
            {% for attachment in ticket_attachments %}
                <li class="list-group-item">
                    <strong>Type:</strong> {{ attachment.attachment_type }}
                    <a href="{{ attachment.attachment.url }}" target="_blank" class="btn btn-primary ml-3">View Attachment</a>
                </li>
            {% empty %}
                <li class="list-group-item">No attachments for this ticket.</li>
            {% endfor %}
        </ul>
        <br>
        <form method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-md-3">
                    <label for="id_status">Status:</label>
                    <select class="form-control" id="id_status" name="status">
                        <option value="Ongoing" {% if ticket.status == "Ongoing" %}selected{% endif %}>Ongoing</option>
                        <option value="Completed" {% if ticket.status == "Completed" %}selected{% endif %}>Completed</option>
                    </select>
                </div>
            </div>
            <button type="submit" class="btn btn-primary mt-3">Update</button>
        </form>
        

        
    {% endblock %}

ticketing_system/accounts/templates/create_ticket.html
{% extends 'base.html' %}
{% block title %}
  Project List
{% endblock %}

{% block content %}
    <h2>Create Ticket</h2>

    <form method="post" class="my-4" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="mb-3">
            <label for="id_name" class="form-label">Name:</label>
            <input type="text" id="id_name" name="name" class="form-control" required />
        </div>

        <div class="mb-3">
            <label for="id_description" class="form-label">Description:</label>
            <textarea id="id_description" name="description" class="form-control" required></textarea>
        </div>

        <div class="mb-3">
            <label for="id_assigned_to" class="form-label">Assigned To:</label>
            <select id="id_assigned_to" name="assigned_to" class="form-select">
                {% for user in users %}
                    <option value="{{ user.id }}">{{ user.username }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="mb-3">
            <label for="id_project" class="form-label">Project:</label>
            <select id="id_project" name="project" class="form-select">
                <option value="{{ project.id }}">{{ project.name }}</option>
            </select>
        </div>

        <div class="mb-3">
            <label for="id_status" class="form-label">Status:</label>
            <select id="id_status" name="status" class="form-select">
                <option value="Draft">Draft</option>
                <option value="Ongoing">Ongoing</option>
                <option value="Completed">Completed</option>
                <option value="Archived">Archived</option>
            </select>
        </div>

        <div class="mb-3">
            <label for="id_attachment" class="form-label">Attachment:</label>
            <input type="file" id="id_attachment" name="attachment" class="form-control" />
        </div>
        
        <div class="mb-3">
            <label for="id_attachment_type" class="form-label">Attachment Type:</label>
            <select id="id_attachment_type" name="attachment_type" class="form-select">
                <option value="Image">Image</option>
                <option value="Video">Video</option>
                <option value="Docs">Docs</option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Create Ticket</button>
    </form>
{% endblock %}

ticketing_system/accounts/templates/edit_project.html
{% extends 'base.html' %}
{% block title %}
  Project List
{% endblock %}

{% block content %}
    <h2>Edit Project</h2>

    <form method="post" action="{% url 'edit_project' project.id %}" class="my-4">
        {% csrf_token %}

        <div class="mb-3">
            <label for="id_name" class="form-label">Name:</label>
            <input type="text" id="id_name" name="name" class="form-control" value="{{ project.name }}" required />
        </div>

        <div class="mb-3">
            <label for="id_description" class="form-label">Description:</label>
            <textarea id="id_description" name="description" class="form-control" required>{{ project.description }}</textarea>
        </div>

        <div class="mb-3">
            <label for="id_status" class="form-label">Status:</label>
            <select id="id_status" name="status" class="form-select">
                <option value="Active" {% if project.status == 'Active' %} selected {% endif %}>Active</option>
                <option value="Inactive" {% if project.status == 'Inactive' %} selected {% endif %}>Inactive</option>
                <option value="Completed" {% if project.status == 'Completed' %} selected {% endif %}>Completed</option>
                <option value="Archived" {% if project.status == 'Archived' %} selected {% endif %}>Archived</option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Update Project</button>
    </form>
    {% endblock %}

ticketing_system/accounts/templates/profile.html
{% extends 'base.html' %}
{% block title %}
    Profile
{% endblock %}
{% block css %}
    <style>
        body {
            background-color: #f8f9fa;
        }
        .profile-container {
            background-color: #ffffff;
            border-radius: 8px;
            padding: 20px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            margin-top: 50px;
        }
        h1 {
            text-align: center;
            margin-bottom: 30px;
        }
        .profile-info {
            font-size: 18px;
            margin-bottom: 15px;
        }
    </style>
    {% endblock %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="profile-container">
                    <h1>User Profile</h1>
                    <div class="profile-info">
                        <p><strong>Username:</strong> {{ user.username }}</p>
                        <p><strong>Email:</strong> {{ user.email }}</p>
                        <p><strong>Number of Projects:</strong> {{ user.projects.count }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endblock %}

ticketing_system/accounts/templates/project_form.html
{% extends 'base.html' %}
{% block title %}
  Project List
{% endblock %}

{% block content %}
    <h2>Project Management</h2>

    <!-- Form for creating/editing projects -->
    <form method="post" action="{% url 'create_project' %}" class="my-4">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_name" class="form-label">Name:</label>
            <input type="text" id="id_name" name="name" class="form-control" required />
        </div>
        <div class="mb-3">
            <label for="id_description" class="form-label">Description:</label>
            <textarea id="id_description" name="description" class="form-control" required></textarea>
        </div>
        <div class="mb-3">
            <label for="id_status" class="form-label">Status:</label>
            <select id="id_status" name="status" class="form-select">
                <option value="Active">Active</option>
                <option value="Inactive">Inactive</option>
                <option value="Completed">Completed</option>
                <option value="Archived">Archived</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Create Project</button>
        <a href="{% url 'project_list' %}" class="btn btn-warning">Project List</a>
    </form>
{% endblock %}

ticketing_system/accounts/templates/project_list.html
{% extends 'base.html' %}
{% block title %}
  Project List
{% endblock %}

{% block content %}
  <h2>Project List</h2>

  {% if request.user.is_superuser %}
  <a href="{% url 'create_project' %}" class="btn btn-primary mb-3">Create New Project</a>
  {% endif %}
  
  <!-- Table to display the list of projects -->
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Status</th>
        {% if request.user.is_superuser %}  <th>Actions</th> {% endif %}
        
      </tr>
    </thead>
    <tbody>
      <!-- Loop through projects -->
      {% for project in projects %}
        <tr>
          <td>{{ project.name }}</td>
          <td>{{ project.description }}</td>
          <td>{{ project.status }}</td>
          {% if request.user.is_superuser %}
          <td>
            <!-- Edit button -->
            <a href="{% url 'edit_project' project.id %}" class="btn btn-sm btn-primary">Edit</a>

            <!-- Block/Unblock button -->
            {% if project.is_blocked %}
              <a href="{% url 'unblock_project' project.id %}" class="btn btn-sm btn-warning">Unblock</a>
            {% else %}
              <a href="{% url 'block_project' project.id %}" class="btn btn-sm btn-secondary">Block</a>
            {% endif %}

            <!-- Delete button -->
            <a href="{% url 'delete_project' project.id %}" class="btn btn-sm btn-danger">Delete</a>

            <!-- Assign button -->
            {% if not project.is_blocked %}
            <a href="{% url 'assign_project' project.id %}" class="btn btn-sm btn-info">Assign User</a>

            
            <!-- Assign ticket button -->
            <a href="{% url 'create_ticket' project.id %}" class="btn btn-sm btn-success">Assign Ticket</a>
            {% endif %}
          </td>
          {% endif %}
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

ticketing_system/accounts/templates/update_ticket_status.html
{% extends 'base.html' %}
{% block title %}
  Project List
{% endblock %}

{% block content %}
  <h2>Update Ticket Status</h2>

  <form method="post">
    {% csrf_token %}
    <label for="id_status">Status:</label>
    <select id="id_status" name="status">
      <option value="Ongoing">Ongoing</option>
      <option value="Completed">Completed</option>
    </select>
    <button type="submit">Update</button>
  </form>
{% endblock %}